format = '$username$sudo[:](bold white) $directory[(\[$git_branch$git_state\])](bold dimmed yellow)$line_break$character'

[username]
format = '[$user]($style)'
style_user = "bold dimmed cyan"
style_root = "bold red"
show_always = true
aliases = { "christoph.aurich@energy2market.de" = "christoph.aurich" }

[sudo]
format = '[$symbol]($style)'
symbol = '*'
style = "bold bright-black"
disabled = false

[directory]
format = '[$path]($style) [$read_only]($read_only_style)'
style = "bold white"
read_only = "[readonly]"
read_only_style = "bright-black"

[git_branch]
format = '[$branch]($style)'
style = 'bold dimmed yellow'

[git_state]
format = '[ | $state( $progress_current/$progress_total)]($style)'
style = 'bold dimmed yellow'

[character]
success_symbol = '[❯](bold white)'
error_symbol = '[❯](bold red)'
